[package]
name = "gitx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
git2 = { version = "0.20.2", default-features = false } # TODO: remove default-features = false in the future
inquire = "0.7.5"

[dev-dependencies]
tempfile = "3.20.0"
